import React, { useEffect, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, BarChart3, Check, Database, Download, Factory, Gauge, Linkedin, Mail, MapPin, Menu, Phone, ShieldCheck, Sparkles, Workflow, Users, X } from 'lucide-react';

const tabs=[['home','Home'],['about','About'],['portfolio','Portfolio'],['service','Service'],['contact','Contact']];
const projects=[
 {icon:Factory,type:'Digital transformation',title:'Smart Factory Digital Roadmap',challenge:'Create a structured path from disconnected factory initiatives to scalable digital operations.',approach:'Coordinated the site roadmap, minimum mandatory requirements, Smart Transformation Stories, stakeholder alignment, and adoption follow-up.',impact:'Improved operational visibility, standardization, governance, and alignment between local priorities and the wider Smart Factory strategy.',metric:'Site roadmap',tags:['Industry 4.0','Roadmapping','Adoption']},
 {icon:Gauge,type:'Operational excellence',title:'Lean Diagnostic Savings',challenge:'Identify hidden capacity losses, waste, and flow constraints across manufacturing processes.',approach:'Applied Lean diagnostics, process observation, data analysis, line balancing, and structured improvement workshops.',impact:'Generated approximately EUR 260,000 in annualized savings through process redesign, productivity improvements, and better resource utilization.',metric:'EUR 260K annual savings',tags:['Lean','VSM','Productivity']},
 {icon:BarChart3,type:'Data and applications',title:'Operational Intelligence',challenge:'Turn fragmented production information into reliable and actionable management insights.',approach:'Designed Tableau dashboards, KPI logic, SQL-enabled data views, and custom single-page web applications.',impact:'Reduced manual reporting effort and enabled faster identification of performance gaps, trends, and priorities.',metric:'Data to action',tags:['Tableau','SQL','Web apps']},
 {icon:ShieldCheck,type:'OT cybersecurity',title:'OT Asset Resilience',challenge:'Maintain accurate visibility of connected production assets and support timely risk remediation.',approach:'Maintained OT inventories using VESTA and Claroty and supported data quality, vulnerability follow-up, governance, and coordination.',impact:'Strengthened asset visibility, compliance, ownership, and response to critical operational technology vulnerabilities.',metric:'Secure operations',tags:['Claroty','Governance','Risk']}
];
const services=[
 {icon:Factory,title:'Industrial Engineering',summary:'Improve workplace design, capacity, flow, and productivity using practical engineering methods.',items:['Time and motion studies','Line balancing and capacity models','Standard work and ergonomics','Material flow analysis'],tools:'Methods engineering | Excel | Gemba'},
 {icon:Sparkles,title:'Lean and Six Sigma',summary:'Build a measurable improvement pipeline and solve recurring operational losses at their source.',items:['Lean diagnostic and opportunity funnel','Value Stream Mapping','Kaizen facilitation','Green Belt problem solving'],tools:'VSM | DMAIC | 5 Why | Kaizen'},
 {icon:Database,title:'Data and Analytics',summary:'Transform factory data into trusted KPIs, clear dashboards, and faster daily decisions.',items:['KPI definition and governance','Tableau dashboards','SQL data preparation','Advanced Excel automation'],tools:'Tableau | SQL | Excel | APIs'},
 {icon:Workflow,title:'Smart Factory Enablement',summary:'Move digital ideas from business need to governed deployment and sustained shop-floor adoption.',items:['Digital maturity assessment','Use-case prioritization','Roadmap and benefit tracking','Change and adoption coaching'],tools:'Roadmaps | MMRs | Agile delivery'},
 {icon:ShieldCheck,title:'OT Cybersecurity Support',summary:'Improve operational asset visibility, accountability, and vulnerability management discipline.',items:['OT inventory quality review','Risk and vulnerability follow-up','Ownership and governance routines','Compliance evidence support'],tools:'Claroty | VESTA | Risk governance'},
 {icon:Users,title:'Production Improvement Coaching',summary:'Help cross-functional teams convert daily production issues into structured improvements.',items:['Performance review routines','Constraint and root-cause analysis','Action tracking','Team workshops and coaching'],tools:'SPS | FMEA | PDCA | Visual management'}
];
function Waves(){const reduce=useReducedMotion(),ys=[145,170,195,220,245,270];return <div className="waves"><motion.svg viewBox="0 0 1280 380" preserveAspectRatio="none" animate={reduce?undefined:{x:[0,-24,0],scaleY:[1,1.07,1]}} transition={{duration:9,repeat:Infinity,ease:'easeInOut'}}><defs><linearGradient id="wave"><stop stopColor="#ef2cff"/><stop offset=".5" stopColor="#793cff"/><stop offset="1" stopColor="#00b7ff"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{ys.map((y,i)=><path key={y} d={`M-60 ${y} C120 ${40+i*24},260 ${320-i*6},420 ${y+20} S720 ${50+i*20},900 ${y} S1170 ${315-i*5},1350 ${y-12}`} fill="none" stroke="url(#wave)" strokeWidth="1.5" opacity={1-i*.1} filter="url(#glow)"/>)}</motion.svg></div>}
function Glass({children,className=''}){return <div className={`glass ${className}`}>{children}</div>}
function Heading({kicker,title,text}){return <div className="heading"><p>{kicker}</p><h2>{title}</h2>{text&&<span>{text}</span>}</div>}
function Nav({active,setActive}){const[open,setOpen]=useState(false),go=id=>{setActive(id);setOpen(false)};return <header><button className="brand" onClick={()=>go('home')}>Portfolio.</button><nav className="desktop-nav">{tabs.map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>go(id)}>{label}{active===id&&<motion.i layoutId="navline"/>}</button>)}</nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><AnimatePresence>{open&&<motion.nav className="mobile-nav" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{tabs.map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}{active===id&&<Check size={15}/>}</button>)}</motion.nav>}</AnimatePresence></header>}
function Profile(){const[src,setSrc]=useState('./profile2.png');return <motion.div className="profile-wrap" initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}}><motion.div className="profile-ring" animate={{rotate:360}} transition={{duration:28,repeat:Infinity,ease:'linear'}}/><div className="profile"><img src={src} onError={()=>setSrc('./profile-placeholder.svg')} alt="John Harley De Leon"/></div></motion.div>}
function Home({go}){return <section className="home section"><motion.div className="hero" initial={{opacity:0,x:-22}} animate={{opacity:1,x:0}}><small>Smart Factory Engineer</small><h1>John Harley<br/>De Leon</h1><h2>Digital Leader <b>&amp;</b> Industrial Engineer</h2><p>Manufacturing professional with more than 10 years of experience connecting industrial engineering, operational excellence, data, and OT cybersecurity to deliver measurable factory results.</p><div className="actions"><a className="primary" href="./John-Harley-De-Leon-CV.pdf" download><Download/>Download CV</a><button onClick={()=>go('portfolio')}>View projects <ArrowUpRight/></button><a className="circle" href="https://www.linkedin.com" aria-label="LinkedIn"><Linkedin/></a><a className="circle" href="mailto:johnharleydeleon@gmail.com" aria-label="Email"><Mail/></a></div></motion.div><Profile/></section>}
function About(){const areas=[['Manufacturing foundation','Methods engineering, production improvement, line balancing, capacity analysis, ergonomics, standard work, and daily shop-floor problem solving.'],['Digital leadership','Smart Factory roadmaps, digital use cases, operational applications, dashboards, and adoption of new ways of working.'],['Data-informed decisions','Gemba observation combined with Tableau, SQL, advanced Excel, KPI design, and structured analysis.'],['Resilient operations','Operational performance connected with OT asset governance and cybersecurity for reliable digital growth.']];return <section className="section"><Heading kicker="About me" title="Engineering progress from the shop floor up." text="A practical blend of manufacturing experience, continuous improvement, digital delivery, analytics, and resilient operations."/><div className="about-grid"><Glass className="about-main"><h3>I translate complex factory challenges into practical systems that teams can understand, adopt, measure, and continuously improve.</h3><hr/><div className="detail-grid">{areas.map(([t,x])=><div key={t}><h4>{t}</h4><p>{x}</p></div>)}</div></Glass><div className="side-grid"><Glass className="metrics"><div><b>10+</b><span>Years</span></div><div><b>EUR 260K</b><span>Savings</span></div><div><b>4</b><span>Disciplines</span></div></Glass>{['Business-focused outcomes','Cross-functional collaboration','Data-driven improvement','Hands-on implementation'].map(x=><Glass className="strength" key={x}>{x}</Glass>)}</div></div></section>}
function Portfolio(){return <section className="section"><Heading kicker="Selected work" title="From roadmap to measurable results." text="Representative initiatives showing how strategy, engineering, analytics, and governance translate into operational value."/><div className="card-grid">{projects.map((p,i)=>{const Icon=p.icon;return <motion.article key={p.title} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:i*.05}}><Glass className="project"><div className="card-top"><i><Icon/></i><em>{p.metric}</em></div><small>{p.type}</small><h3>{p.title}</h3><div className="case"><p><b>Challenge:</b> {p.challenge}</p><p><b>Approach:</b> {p.approach}</p><p><b>Impact:</b> {p.impact}</p></div><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></Glass></motion.article>})}</div></section>}
function Service(){return <section className="section"><Heading kicker="Core expertise" title="Connected services for a smarter factory." text="Support ranges from focused diagnostics and dashboards to transformation programs and capability building."/><div className="service-grid">{services.map((s,i)=>{const Icon=s.icon;return <Glass className="service" key={s.title}><div className="card-top"><i><Icon/></i><em>0{i+1}</em></div><h3>{s.title}</h3><p>{s.summary}</p><small>Typical deliverables</small><ul>{s.items.map(x=><li key={x}><Check/>{x}</li>)}</ul><footer>{s.tools}</footer></Glass>})}</div></section>}
function Contact(){const[ok,setOk]=useState(false),copy=async()=>{try{await navigator.clipboard.writeText('johnharleydeleon@gmail.com');setOk(true);setTimeout(()=>setOk(false),1500)}catch{location.href='mailto:johnharleydeleon@gmail.com'}};return <section className="contact section"><div><Heading kicker="Get in touch" title="Let's improve how manufacturing works." text="Open to conversations about Smart Factory transformation, industrial engineering, analytics, continuous improvement, and OT cybersecurity."/><div className="actions"><a className="primary" href="mailto:johnharleydeleon@gmail.com"><Mail/>Send an email</a><button onClick={copy}>{ok?<Check/>:<Download/>}{ok?'Email copied':'Copy email'}</button></div></div><Glass className="contact-card"><a href="mailto:johnharleydeleon@gmail.com"><Mail/><span><small>Email</small>johnharleydeleon@gmail.com</span></a><a href="tel:+36306138167"><Phone/><span><small>Phone</small>+36 30 613 8167</span></a><div><MapPin/><span><small>Location</small>Gyongyos, Hungary</span></div></Glass></section>}
export default function App(){const[active,setActive]=useState('home'),reduce=useReducedMotion();useEffect(()=>{const key=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;const i=tabs.findIndex(([id])=>id===active),n=(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setActive(tabs[n][0])};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[active]);const views={home:<Home go={setActive}/>,about:<About/>,portfolio:<Portfolio/>,service:<Service/>,contact:<Contact/>};return <div className="app"><div className="background"/><Waves/><Glass className="shell"><Nav active={active} setActive={setActive}/><main><AnimatePresence mode="wait"><motion.div key={active} className="view" initial={reduce?{opacity:0}:{opacity:0,y:12,filter:'blur(6px)'}} animate={{opacity:1,y:0,filter:'blur(0)'}} exit={reduce?{opacity:0}:{opacity:0,y:-8}}>{views[active]}</motion.div></AnimatePresence></main></Glass></div>}
